apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: devops
spec:
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: l_docker:dind
        securityContext:
            privileged: true
        resources:
          limits:
            memory: 3Gi
            cpu: 1000m
          requests:
            cpu: 10m
            memory: 256Mi
